export const data = [
  { id: 1, username: "Samuel", height: "16", gender: "male", location: "Kenya", age: "20", position: "attacking" },
  { id: 2, username: "David", height: "18", gender: "male", location: "South Africa", age: "24", position: "striker" },
  { id: 3, username: "Ahmed", height: "17", gender: "male", location: "Algeria", age: "21", position: "keeper" },
  { id: 4, username: "Peter", height: "19", gender: "male", location: "Tanzania", age: "22", position: "defender" },
  { id: 5, username: "John", height: "20", gender: "male", location: "Gambia", age: "25", position: "striker" },
  { id: 6, username: "Paul", height: "18", gender: "male", location: "Rwanda", age: "23", position: "midfielder" },
  { id: 7, username: "Joseph", height: "17", gender: "male", location: "Nigeria", age: "21", position: "winger" },
  { id: 8, username: "Emmanuel", height: "16", gender: "male", location: "Ghana", age: "20", position: "forward" },
  { id: 9, username: "Daniel", height: "15", gender: "male", location: "Uganda", age: "22", position: "defender" },
  { id: 10, username: "Michael", height: "19", gender: "male", location: "Cameroon", age: "24", position: "midfielder" },
  { id: 11, username: "Stephen", height: "14", gender: "male", location: "Zambia", age: "19", position: "keeper" },
  { id: 12, username: "James", height: "18", gender: "male", location: "Zimbabwe", age: "23", position: "striker" },
  { id: 13, username: "Henry", height: "16", gender: "male", location: "Malawi", age: "20", position: "attacking" },
  { id: 14, username: "Victor", height: "17", gender: "male", location: "Burundi", age: "21", position: "winger" },
  { id: 15, username: "Ibrahim", height: "15", gender: "male", location: "Mali", age: "22", position: "defender" },
  { id: 16, username: "Abdul", height: "19", gender: "male", location: "Niger", age: "24", position: "midfielder" },
  { id: 17, username: "Mustapha", height: "20", gender: "male", location: "Chad", age: "25", position: "striker" },
  { id: 18, username: "Tunde", height: "18", gender: "male", location: "Benin", age: "23", position: "forward" },
  { id: 19, username: "Olu", height: "17", gender: "male", location: "Togo", age: "21", position: "keeper" },
  { id: 20, username: "Kofi", height: "16", gender: "male", location: "Ghana", age: "20", position: "attacking" },
  { id: 21, username: "Kwame", height: "15", gender: "male", location: "Liberia", age: "22", position: "defender" },
  { id: 22, username: "Bola", height: "19", gender: "male", location: "Nigeria", age: "24", position: "midfielder" },
  { id: 23, username: "Chinedu", height: "18", gender: "male", location: "Nigeria", age: "23", position: "winger" },
  { id: 24, username: "Obinna", height: "17", gender: "male", location: "Nigeria", age: "21", position: "striker" },
  { id: 25, username: "Femi", height: "16", gender: "male", location: "Nigeria", age: "20", position: "forward" },
  { id: 26, username: "Amina", height: "15", gender: "female", location: "Sudan", age: "22", position: "defender" },
  { id: 27, username: "Fatima", height: "19", gender: "female", location: "Somalia", age: "24", position: "midfielder" },
  { id: 28, username: "Zainab", height: "18", gender: "female", location: "Djibouti", age: "23", position: "keeper" },
  { id: 29, username: "Maryam", height: "17", gender: "female", location: "Morocco", age: "21", position: "attacking" },
  { id: 30, username: "Halima", height: "16", gender: "female", location: "Tunisia", age: "20", position: "winger" },
  { id: 31, username: "Jamila", height: "15", gender: "female", location: "Libya", age: "22", position: "defender" },
  { id: 32, username: "Noura", height: "19", gender: "female", location: "Egypt", age: "24", position: "midfielder" },
  { id: 33, username: "Aisha", height: "18", gender: "female", location: "Mauritania", age: "23", position: "striker" },
  { id: 34, username: "Salma", height: "17", gender: "female", location: "Comoros", age: "21", position: "forward" },
  { id: 35, username: "Ruqayyah", height: "16", gender: "female", location: "Ethiopia", age: "20", position: "keeper" },
  { id: 36, username: "Grace", height: "15", gender: "female", location: "South Sudan", age: "22", position: "attacking" },
  { id: 37, username: "Linda", height: "19", gender: "female", location: "Kenya", age: "24", position: "winger" },
  { id: 38, username: "Esther", height: "18", gender: "female", location: "Uganda", age: "23", position: "defender" },
  { id: 39, username: "Joy", height: "17", gender: "female", location: "Tanzania", age: "21", position: "midfielder" },
  { id: 40, username: "Deborah", height: "16", gender: "female", location: "Rwanda", age: "20", position: "striker" },
  { id: 41, username: "Rebecca", height: "15", gender: "female", location: "Burkina Faso", age: "22", position: "forward" },
  { id: 42, username: "Naomi", height: "19", gender: "female", location: "Central African Republic", age: "24", position: "keeper" },
  { id: 43, username: "Mercy", height: "18", gender: "female", location: "Guinea", age: "23", position: "attacking" },
  { id: 44, username: "Florence", height: "17", gender: "female", location: "Sierra Leone", age: "21", position: "winger" },
  { id: 45, username: "Ruth", height: "16", gender: "female", location: "Côte d'Ivoire", age: "20", position: "defender" },
  { id: 46, username: "Janet", height: "15", gender: "female", location: "Senegal", age: "22", position: "midfielder" },
  { id: 47, username: "Patience", height: "19", gender: "female", location: "Gabon", age: "24", position: "striker" },
  { id: 48, username: "Hope", height: "18", gender: "female", location: "Equatorial Guinea", age: "23", position: "forward" },
  { id: 49, username: "Rose", height: "17", gender: "female", location: "Mozambique", age: "21", position: "keeper" }
]